name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在标签为 vX.X.X 时触发
    branches:
      - dev  # dev 分支依然触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Build Docker image
      run: docker build -t luo-api .

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Convert repository name to lowercase and Push Docker image to GHCR
      run: |
        LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          TAG="dev"
        else
          TAG="${GITHUB_REF#refs/tags/}"  # 获取标签名
        fi
        docker tag luo-api ghcr.io/$LOWERCASE_REPO:$TAG
        docker push ghcr.io/$LOWERCASE_REPO:$TAG
